// POV-Ray scene generated by MolScriptSVG 2.1.5
// Copyright (C) 1997-1998 Per J. Kraulis
// title: c-H-ras p21 protein (1-166), complex with GDP and Mg
// fitted orthographic camera: distance=44.279726 right=41.697006 up=38.771899
#version 3.7;
global_settings { assumed_gamma 1.0 ambient_light rgb <0.25, 0.25, 0.25> }
background { color rgb <1.000000, 1.000000, 1.000000> }
camera {
  orthographic
  location <0.123305, 0.523638, -45.399440>
  look_at <0.123305, 0.523638, -1.119714>
  right <41.697006, 0, 0>
  up <0, 38.771899, 0>
}
// trace from 1 to 166 (166 residues)
cylinder {
  <-9.288754, -11.561690, 16.980149>, <-6.851141, -12.030539, 14.065478>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-6.851141, -12.030539, 14.065478>, <-4.079336, -9.561905, 13.126003>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-4.079336, -9.561905, 13.126003>, <-3.277205, -8.504540, 9.532937>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-3.277205, -8.504540, 9.532937>, <-0.738523, -5.912014, 8.297542>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-0.738523, -5.912014, 8.297542>, <-1.841840, -3.428633, 5.592024>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.841840, -3.428633, 5.592024>, <1.649499, -2.912551, 4.095944>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <1.649499, -2.912551, 4.095944>, <0.867637, 0.342368, 2.197234>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <0.867637, 0.342368, 2.197234>, <3.238120, 1.563784, -0.559628>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <3.238120, 1.563784, -0.559628>, <2.793434, 4.269090, -3.234852>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <2.793434, 4.269090, -3.234852>, <3.911874, 7.701894, -4.487985>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <3.911874, 7.701894, -4.487985>, <4.500056, 10.443644, -1.884080>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <4.500056, 10.443644, -1.884080>, <1.323120, 12.522148, -2.377472>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <1.323120, 12.522148, -2.377472>, <-1.194210, 9.971508, -3.784911>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.194210, 9.971508, -3.784911>, <-3.004886, 10.237755, -0.413701>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-3.004886, 10.237755, -0.413701>, <-1.727144, 7.151765, 1.472876>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.727144, 7.151765, 1.472876>, <-1.695829, 8.875680, 4.883413>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.695829, 8.875680, 4.883413>, <-4.956395, 10.874138, 4.416531>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-4.956395, 10.874138, 4.416531>, <-6.563768, 7.474690, 3.653226>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-6.563768, 7.474690, 3.653226>, <-5.223671, 5.824204, 6.839043>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-5.223671, 5.824204, 6.839043>, <-5.997465, 8.719204, 9.267893>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-5.997465, 8.719204, 9.267893>, <-9.431691, 8.917634, 7.605320>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-9.431691, 8.917634, 7.605320>, <-10.452921, 5.403708, 8.732928>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-10.452921, 5.403708, 8.732928>, <-8.982620, 6.368798, 12.153719>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-8.982620, 6.368798, 12.153719>, <-9.529743, 10.039453, 13.217384>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-9.529743, 10.039453, 13.217384>, <-12.199609, 10.374950, 10.464789>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-12.199609, 10.374950, 10.464789>, <-11.372671, 13.718465, 8.783624>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-11.372671, 13.718465, 8.783624>, <-9.825767, 15.009910, 5.525898>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-9.825767, 15.009910, 5.525898>, <-6.234791, 16.142036, 6.232021>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-6.234791, 16.142036, 6.232021>, <-4.429608, 18.369587, 3.690032>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-4.429608, 18.369587, 3.690032>, <-1.049169, 18.138372, 5.503245>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.049169, 18.138372, 5.503245>, <-0.372129, 15.250267, 7.922178>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-0.372129, 15.250267, 7.922178>, <3.354201, 16.100481, 8.226572>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <3.354201, 16.100481, 8.226572>, <5.041806, 13.929242, 5.537732>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <5.041806, 13.929242, 5.537732>, <8.124975, 13.837768, 7.833052>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <8.124975, 13.837768, 7.833052>, <6.547108, 11.329324, 10.268758>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <6.547108, 11.329324, 10.268758>, <6.822149, 7.508759, 10.247245>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <6.822149, 7.508759, 10.247245>, <4.624614, 5.529845, 12.683459>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <4.624614, 5.529845, 12.683459>, <2.297567, 2.487321, 12.702398>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <2.297567, 2.487321, 12.702398>, <-1.433229, 3.344697, 12.779995>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.433229, 3.344697, 12.779995>, <-3.737630, 0.553233, 14.023496>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-3.737630, 0.553233, 14.023496>, <-7.544039, 0.292596, 13.790691>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-7.544039, 0.292596, 13.790691>, <-10.027368, -2.178485, 15.333514>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-10.027368, -2.178485, 15.333514>, <-13.031023, -2.694622, 13.021044>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-13.031023, -2.694622, 13.021044>, <-15.332070, -5.530895, 11.873051>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-15.332070, -5.530895, 11.873051>, <-15.126449, -6.963361, 8.326873>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-15.126449, -6.963361, 8.326873>, <-18.220946, -9.215514, 8.257080>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-18.220946, -9.215514, 8.257080>, <-19.185198, -10.364706, 11.781780>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-19.185198, -10.364706, 11.781780>, <-15.548631, -10.819492, 12.891289>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-15.548631, -10.819492, 12.891289>, <-13.516428, -8.002078, 14.504867>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-13.516428, -8.002078, 14.504867>, <-9.849100, -8.131459, 13.408461>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-9.849100, -8.131459, 13.408461>, <-7.015331, -5.798120, 14.499874>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-7.015331, -5.798120, 14.499874>, <-5.489522, -4.254578, 11.347807>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-5.489522, -4.254578, 11.347807>, <-1.998610, -2.780399, 11.895777>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.998610, -2.780399, 11.895777>, <-1.967808, -0.271950, 9.006433>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.967808, -0.271950, 9.006433>, <1.576247, 0.572395, 7.845787>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <1.576247, 0.572395, 7.845787>, <1.606691, 4.104875, 6.371900>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <1.606691, 4.104875, 6.371900>, <5.274236, 4.675877, 5.430697>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <5.274236, 4.675877, 5.430697>, <6.428937, 8.298427, 4.969569>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <6.428937, 8.298427, 4.969569>, <9.203841, 10.088336, 3.016260>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <9.203841, 10.088336, 3.016260>, <12.590898, 10.080044, 4.818363>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <12.590898, 10.080044, 4.818363>, <15.568373, 9.582529, 2.462788>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <15.568373, 9.582529, 2.462788>, <19.070084, 8.136274, 3.088555>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <19.070084, 8.136274, 3.088555>, <19.431808, 4.646011, 4.645962>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <19.431808, 4.646011, 4.645962>, <16.046614, 2.883469, 5.012603>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <16.046614, 2.883469, 5.012603>, <16.130665, -0.672605, 6.434835>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <16.130665, -0.672605, 6.434835>, <12.880189, -0.452584, 8.475025>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <12.880189, -0.452584, 8.475025>, <10.670901, 0.002230, 5.379205>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <10.670901, 0.002230, 5.379205>, <12.287479, -3.053294, 3.746509>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <12.287479, -3.053294, 3.746509>, <11.915698, -5.118433, 6.938401>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <11.915698, -5.118433, 6.938401>, <8.180240, -4.300372, 6.959388>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <8.180240, -4.300372, 6.959388>, <7.953299, -5.544815, 3.350862>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <7.953299, -5.544815, 3.350862>, <8.954146, -8.967725, 4.781414>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <8.954146, -8.967725, 4.781414>, <6.796569, -8.895571, 7.958837>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <6.796569, -8.895571, 7.958837>, <3.426785, -7.465204, 6.789341>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <3.426785, -7.465204, 6.789341>, <1.509295, -9.233720, 3.978915>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <1.509295, -9.233720, 3.978915>, <-1.291127, -6.997973, 2.606646>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.291127, -6.997973, 2.606646>, <0.104121, -4.665318, -0.079578>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <0.104121, -4.665318, -0.079578>, <-2.092442, -1.621010, -0.787808>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-2.092442, -1.621010, -0.787808>, <-0.131766, -0.234912, -3.769188>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-0.131766, -0.234912, -3.769188>, <-1.606329, 3.307634, -3.773998>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.606329, 3.307634, -3.773998>, <-1.427560, 5.130847, -7.121926>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.427560, 5.130847, -7.121926>, <-2.979203, 8.580667, -7.734956>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-2.979203, 8.580667, -7.734956>, <-4.799563, 8.423094, -11.096058>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-4.799563, 8.423094, -11.096058>, <-4.513202, 12.239708, -11.409288>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-4.513202, 12.239708, -11.409288>, <-0.709122, 12.149180, -11.025367>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-0.709122, 12.149180, -11.025367>, <0.564591, 9.410806, -13.421503>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <0.564591, 9.410806, -13.421503>, <3.970739, 9.254867, -11.650850>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <3.970739, 9.254867, -11.650850>, <2.296713, 7.006584, -9.053823>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <2.296713, 7.006584, -9.053823>, <1.512537, 4.522794, -11.864227>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <1.512537, 4.522794, -11.864227>, <5.211528, 4.298616, -12.798131>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <5.211528, 4.298616, -12.798131>, <5.900341, 4.049857, -9.031384>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <5.900341, 4.049857, -9.031384>, <3.710613, 0.912882, -8.753246>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <3.710613, 0.912882, -8.753246>, <5.579840, -0.775278, -11.651245>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <5.579840, -0.775278, -11.651245>, <8.897559, -0.859025, -9.721361>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <8.897559, -0.859025, -9.721361>, <7.205474, -0.994086, -6.287047>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <7.205474, -0.994086, -6.287047>, <5.687039, -4.319160, -7.477532>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <5.687039, -4.319160, -7.477532>, <9.170080, -5.859052, -7.816681>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <9.170080, -5.859052, -7.816681>, <10.898958, -5.064553, -4.545949>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <10.898958, -5.064553, -4.545949>, <7.993060, -6.838728, -2.802425>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <7.993060, -6.838728, -2.802425>, <8.977494, -9.940925, -4.754010>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <8.977494, -9.940925, -4.754010>, <12.544923, -9.250096, -3.538699>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <12.544923, -9.250096, -3.538699>, <11.772588, -9.244821, 0.174210>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <11.772588, -9.244821, 0.174210>, <9.403787, -12.253945, 0.271291>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <9.403787, -12.253945, 0.271291>, <11.513131, -13.647478, -2.631591>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <11.513131, -13.647478, -2.631591>, <8.361926, -14.847035, -4.445174>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <8.361926, -14.847035, -4.445174>, <5.359889, -13.637710, -6.486042>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <5.359889, -13.637710, -6.486042>, <2.340674, -14.684195, -4.374990>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <2.340674, -14.684195, -4.374990>, <1.412617, -11.836367, -1.978614>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <1.412617, -11.836367, -1.978614>, <-2.193568, -10.675616, -1.522494>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-2.193568, -10.675616, -1.522494>, <-1.431269, -7.696945, -3.797674>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.431269, -7.696945, -3.797674>, <-3.974683, -4.860517, -4.324355>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-3.974683, -4.860517, -4.324355>, <-3.445041, -1.895163, -6.693193>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-3.445041, -1.895163, -6.693193>, <-5.691668, 0.993054, -5.654482>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-5.691668, 0.993054, -5.654482>, <-6.162476, 4.276854, -7.563711>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-6.162476, 4.276854, -7.563711>, <-6.427769, 7.151510, -5.050011>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-6.427769, 7.151510, -5.050011>, <-7.664667, 10.640052, -6.036115>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-7.664667, 10.640052, -6.036115>, <-10.654936, 9.308219, -8.026946>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-10.654936, 9.308219, -8.026946>, <-13.030069, 12.082783, -6.836084>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-13.030069, 12.082783, -6.836084>, <-12.220840, 14.596954, -9.613181>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-12.220840, 14.596954, -9.613181>, <-12.695476, 15.074857, -13.389379>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-12.695476, 15.074857, -13.389379>, <-9.003380, 15.345680, -14.413062>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-9.003380, 15.345680, -14.413062>, <-8.491348, 11.642723, -15.258115>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-8.491348, 11.642723, -15.258115>, <-4.900497, 11.392740, -16.555620>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-4.900497, 11.392740, -16.555620>, <-5.033629, 7.604955, -15.988824>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-5.033629, 7.604955, -15.988824>, <-8.004205, 5.997105, -17.800364>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-8.004205, 5.997105, -17.800364>, <-9.461878, 2.850888, -16.177570>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-9.461878, 2.850888, -16.177570>, <-8.232591, 0.882814, -19.219577>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-8.232591, 0.882814, -19.219577>, <-4.606990, 1.612052, -18.312538>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-4.606990, 1.612052, -18.312538>, <-4.955551, 0.487418, -14.677778>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-4.955551, 0.487418, -14.677778>, <-6.936754, -2.519114, -15.969482>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-6.936754, -2.519114, -15.969482>, <-4.154257, -3.528676, -18.388763>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-4.154257, -3.528676, -18.388763>, <-1.383535, -3.133057, -15.764686>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.383535, -3.133057, -15.764686>, <-3.101252, -4.651818, -12.702526>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-3.101252, -4.651818, -12.702526>, <-5.002769, -7.398861, -14.598101>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-5.002769, -7.398861, -14.598101>, <-1.640855, -8.378459, -16.118616>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-1.640855, -8.378459, -16.118616>, <-0.078342, -9.211693, -12.727683>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-0.078342, -9.211693, -12.727683>, <-3.401775, -10.860688, -11.739487>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-3.401775, -10.860688, -11.739487>, <-4.184840, -8.368101, -8.955932>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-4.184840, -8.368101, -8.955932>, <-7.527439, -6.663977, -8.103821>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-7.527439, -6.663977, -8.103821>, <-7.916095, -2.980227, -9.089406>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-7.916095, -2.980227, -9.089406>, <-10.066068, -0.607350, -6.979862>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-10.066068, -0.607350, -6.979862>, <-10.654208, 3.163340, -6.573321>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-10.654208, 3.163340, -6.573321>, <-10.213768, 5.420046, -3.506778>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-10.213768, 5.420046, -3.506778>, <-10.684767, 9.080349, -2.508083>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-10.684767, 9.080349, -2.508083>, <-9.859409, 10.333393, 1.014136>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-9.859409, 10.333393, 1.014136>, <-11.819951, 13.523379, 0.139301>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-11.819951, 13.523379, 0.139301>, <-15.076637, 11.597539, 0.820073>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-15.076637, 11.597539, 0.820073>, <-14.221233, 8.009142, 1.951736>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-14.221233, 8.009142, 1.951736>, <-15.131565, 6.910762, -1.607233>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-15.131565, 6.910762, -1.607233>, <-13.544178, 3.495161, -2.301960>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-13.544178, 3.495161, -2.301960>, <-11.654314, 3.425425, 1.043887>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-11.654314, 3.425425, 1.043887>, <-14.033426, 0.624324, 2.134185>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-14.033426, 0.624324, 2.134185>, <-13.509710, -1.437268, -1.052607>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-13.509710, -1.437268, -1.052607>, <-9.702903, -1.355117, -0.601161>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-9.702903, -1.355117, -0.601161>, <-9.397300, -2.193503, 3.121584>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-9.397300, -2.193503, 3.121584>, <-12.138370, -4.870701, 2.861765>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-12.138370, -4.870701, 2.861765>, <-10.849115, -6.584414, -0.321940>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-10.849115, -6.584414, -0.321940>, <-7.409693, -6.571790, 1.378372>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-7.409693, -6.571790, 1.378372>, <-8.437561, -8.732830, 4.373032>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-8.437561, -8.732830, 4.373032>, <-10.371507, -10.968491, 1.928764>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-10.371507, -10.968491, 1.928764>, <-7.196544, -11.685632, -0.092915>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-7.196544, -11.685632, -0.092915>, <-5.120713, -12.563664, 3.005564>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-5.120713, -12.563664, 3.005564>, <-7.860736, -14.850095, 4.401474>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-7.860736, -14.850095, 4.401474>, <-8.320246, -16.894907, 1.193940>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
cylinder {
  <-8.320246, -16.894907, 1.193940>, <-4.518991, -17.322311, 0.939194>, 0.040000
  texture {
  pigment { color rgbt <1.000000, 0.000000, 0.000000, 0.000000> }
  finish { ambient 0.1200 diffuse 0.85 phong 0.2000 phong_size 32.00 }
}
}
light_source { <-24.894899, 23.786777, -45.399440> color rgb <1, 1, 1> }
light_source { <29.311209, 12.155208, -36.543495> color rgb <0.60, 0.60, 0.60> shadowless }
light_source { <-16.555497, -30.493881, -27.687549> color rgb <0.40, 0.40, 0.40> shadowless }
